# Generated by Django 3.2.6 on 2022-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220408_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer_url',
            field=models.SlugField(default=False, max_length=130, verbose_name='TrailerUrl'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Year'),
        ),
    ]
