# Generated by Django 3.2.6 on 2022-04-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220408_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='trailer_url',
            field=models.SlugField(default='', max_length=130, verbose_name='TrailerUrl'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
