# Generated by Django 4.0.4 on 2022-04-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220408_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='movie'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ratingstars', verbose_name='star'),
        ),
    ]
