# Generated by Django 4.0.4 on 2022-05-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_ratings_movie_alter_ratings_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
